# Introduction NumPy

библиотека для вычислительных опреаций

In [1]:
import numpy as np

In [2]:
x=[2,3,4,6]
y=np.array(x)

print type(x), x
print type(y), y

<type 'list'> [2, 3, 4, 6]
<type 'numpy.ndarray'> [2 3 4 6]


In [3]:
print x[1:3]
print y[1:3]

[3, 4]
[3 4]


In [4]:
#это будет работать только с Numpy масивами:
print y[[0,2]]
print y[y>2]
print y*5
print y**2

[2 4]
[3 4 6]
[10 15 20 30]
[ 4  9 16 36]


# Двумерный массив

In [5]:
matrix = [[1,2,4],[3,1,0]]
nd_matrix=np.array(matrix)

In [6]:
print (matrix[1][2])
print (nd_matrix[1][2])

#only NumPy
print (nd_matrix[1, 2])

0
0
0


# Numpy : Случайные числа

In [7]:
print np.random.rand() # в равномерном распределении
print np.random.randn() #в нормальномализированом распределении

print np.random.randn(3, 4)

0.496887069274
0.907996038055
[[-0.32678868  1.58821638  0.48455647 -1.45654327]
 [ 0.87499599  0.08027286  1.67074662  0.42960775]
 [-0.57188313 -1.33780091 -1.56391525 -0.86449714]]


# Numpy : ARANGE

In [17]:
print np.arange(0,8,0.1)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4
  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9
  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4
  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9
  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3  7.4
  7.5  7.6  7.7  7.8  7.9]


In [18]:
%timeit np.arange(0, 10000)
%timeit range(0, 10000)

10000 loops, best of 3: 23.3 µs per loop
10000 loops, best of 3: 195 µs per loop
